import { withRelatedProject } from '@vercel/related-projects'
import { draftMode } from 'next/headers'
import { VisualEditing } from 'next-sanity/visual-editing'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

console.log(
  'build time',
  process.env.VERCEL_RELATED_PROJECTS,
  process.env.NEXT_PUBLIC_VERCEL_RELATED_PROJECTS
)
const studioUrl = withRelatedProject({
  projectName: 'cv-studio',
  defaultHost: 'http://localhost:3333',
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { isEnabled: isDraftMode } = await draftMode()
  return (
    <html lang="en">
      <body data-studio-url={studioUrl}>
        {children}
        {isDraftMode && <VisualEditing />}
      </body>
    </html>
  )
}
