import { withRelatedProject } from '@vercel/related-projects'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

console.log(
  'build time',
  process.env.VERCEL_RELATED_PROJECTS,
  process.env.NEXT_PUBLIC_VERCEL_RELATED_PROJECTS
)
const studioUrl = withRelatedProject({
  projectName: 'cv-studio',
  defaultHost: 'http://localhost:3333',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-studio-url={studioUrl}>{children}</body>
    </html>
  )
}
