export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

console.log(
  'build time',
  process.env.VERCEL_RELATED_PROJECTS,
  process.env.NEXT_PUBLIC_VERCEL_RELATED_PROJECTS
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
